apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
  name: {{ include "qdrant.fullname" . }}
spec:
  host: {{ .Release.Name }}.default.svc.cluster.local
